### ISSUE TITLE
Device_id 这个参数是怎么获取的 求教。。

### ISSUE THREAD

**Issue by MIkeeJY** [usualwyy/aweme-algorithm#1]
旧版本的这个参数如何生成的，
https://github.com/MIkeeJY/honglou/issues/2 还有新版so库的算法求解

**Comment by NeoTheCapt** [comment]
device_ID是/service/2/device_register/接口返回的，你抓包看就知道了，我的代码里写了这个接口的加解密算法，另外android版的算法和ios版不一样，调用的服务器接口地址也不同。
