### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by DanielAscher** [usualwyy/aweme-algorithm#3]
Hi,

Sorry, i cant speak chinese. I wanted to try this out but i can not use this (can not compile the .so file).

All i want to do is to be able to generate the /v2/register_device encrypted body ... how can i do this?

**Comment by NeoTheCapt** [comment]
This project is mainly about encrypt/decrypt/hash algorithm against Aweme.
The register_device API you mentioned has also been figure out, check the "aweme-aes" folder.

**Comment by DanielAscher** [comment]
hi, Thanks for answering.

Yes i found the aweme-aes. sadly, i cant see the AES function there? I am horrible at C or C++ i can code python thought.

also, when i try the go server (main.go) and i try to hit localhost:9999/deviceReg i get following error:

`Error:failed to load libary.
/root/dev/aweme_aes/libaweme_aes.so: cannot open shared object file: Permission denied
/tmp/go-build224987680/b001/exe/main: undefined symbol: Encode
`

how am i able to get libaweme_aes.so ? i cant compile the files in aweme-aes either. 


edit: what i want to do is either use your go server to send device data to /deviceReg and get back the encrypted post body so i can send it to aweme, or to get the aes funtion so i can use it on my own code.

**Comment by NeoTheCapt** [comment]
The libary you missed is "aweme-aes".
Compile the C project "aweme-aes" so you will get the libary as .so file, then put it in "/root/dev/aweme_aes/".

**Comment by NeoTheCapt** [comment]
In order to compile  aweme-aes, you have to modify the CMakeLists.txt which provide the right config for cmake compiler.

**Comment by DanielAscher** [comment]
ive seen the cmakelists.txt file and as said, im very bad at c or c++

also, is this line important:
`include_directories(/Applications/IDA\ Pro\ 7.0/ida.app/Contents/MacOS/plugins/)`

because i am not on OSX ...

**Comment by NeoTheCapt** [comment]
CMAKE is a cross platform compiler, you can work with it at any OS, all you need is make the path correct.
Also you can choose any other compiler as you wish.

**Comment by DanielAscher** [comment]
yes but i do need to have IDA pro 7.0 installed to compile this?

because right now, when i do a cmake . and get the files, i guess i have to run the make command on those files then.

and it throws just a shitload of errors like: 

`In file included from /home/daniel/go/aweme-algorithm-master/aweme-aes/main.cpp:4:0:
/home/daniel/go/aweme-algorithm-master/aweme-aes/subs.h: At global scope:
/home/daniel/go/aweme-algorithm-master/aweme-aes/subs.h:8:1: error: ‘__int64’ does not name a type; did you mean ‘__int64_t’?
 __int64 aweme_aes(__int64 plainStr, __int64 plainStr_length, __int64 key, __int64 key_length, __int64 strOut);
 ^~~~~~~
 __int64_t
`

**Comment by NeoTheCapt** [comment]
Yes, you do need the IDA.Whatever you install it or not, at least you need the "plugins" folder cuz my code import a file "defs.h" which comes from the "plugins" folder.

**Comment by DanielAscher** [comment]
allright i have install ida free put the plugins folder doesnt even contain a defs.h file ?

**Comment by NeoTheCapt** [comment]
Haha,idk.

**Comment by DanielAscher** [comment]
ok that sucks lmao.

i got a defs.h file so some of the errors have gone away. im still at loss with these errors:

`/usr/include/c++/7/bits/basic_string.h:1249:18: error: ‘_M_append’ was not declared in this scope
  return _M_append(__s, __n);
         ~~~~~~~~~^~~~~~~~~~
`

the fuck? these errors dont seem to come from your code do they?

you got a precompiled .so file somewhere for download to test this thing?

**Comment by NeoTheCapt** [comment]
Sorry, I did my work under MacOS and my precompiled binary doesnt fit you for sure.
You should figure it out by yourself.Google it and solve it,dude.

**Comment by DanielAscher** [comment]
allright. lets see if i can still find my old osx pc to see if this compiles under osx or not

**Comment by NeoTheCapt** [comment]
Ok

**Comment by DanielAscher** [comment]
okay im really stupid but i got it to compile on osx. the api even returns the code. i just have to see if this code is still valid or not.

do you have any idea if i can compile a .so file under osx that works under linux or even windows?

**Comment by DanielAscher** [comment]
also what does that even take? a base64 string of the data i want to send or raw data?

**Comment by NeoTheCapt** [comment]
It will absolutely works fine at any OS since my code rely on no native OS API.
It's been months since I stop this project,I dont exactly remember why I codz the output with base64, maybe for the language bridge purpose,idk.
Anyway,in golang code, the base64 string will be decode.

**Comment by DanielAscher** [comment]
output as base64 is absolutely fine because the if not, the crypted output is unusable.

but does the INPUT need to be base64?

**Comment by NeoTheCapt** [comment]
Check out my code, you will find what you want there
router.go ->func r_deviceReg()

**Comment by DanielAscher** [comment]
Am i reading that right that it needs a post FORM with name hardInfo and as key the base64 of that hardware info?

**Comment by NeoTheCapt** [comment]
No, you are not.
I'm not willing to teach your Golang lessons.Do some learning work from google and finally you will get it work well.

**Comment by DanielAscher** [comment]
ok got it working. sadly, this does not generate a valid log to register a new device
